
name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop
env:
  IMAGE_NAME: ${{github.event.repository.name}}
jobs:
  extract-vars:
    name: Get build vars
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.imageTag }}
      env: ${{ steps.define_env.outputs.env }}
      branch-name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Define env to deploy
        shell: bash
        run: |
          if [[ ${{steps.extract_branch.outputs.branch}} =~ main ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=snapshot" >> $GITHUB_OUTPUT
          fi
        id: define_env

      - name: Get image tag from shortSHA
        id: tag
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "imageTag=${calculatedSha}-${{steps.extract_branch.outputs.branch}}" >> $GITHUB_OUTPUT
  # This pushes the image to GitHub Packages.
  push-backend:
    name: Build and push backend
    runs-on: ubuntu-latest
    needs:
      - extract-vars
    permissions:
      packages: write
      contents: read
      #
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # v4.0.0
        with:
          cache-read-only: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Gradle
        env:
          GRADLE_OPTS: "-XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m"
          JAVA_OPTS: "-XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m"
        run: |
          ./gradlew build --no-daemon --debug
          mkdir -p build/dependency && (cd build/dependency; jar -xf ../libs/*.jar)
        working-directory: ./backend

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/arm64
            linux/amd64
          context: ./backend
          push: true
          tags: |
            ghcr.io/fbsabalete/backend-${{ env.IMAGE_NAME }}:latest
            ghcr.io/fbsabalete/backend-${{ env.IMAGE_NAME }}:${{needs.extract-vars.outputs.image-tag}}

  push-frontend:
    name: Build and push frontend
    runs-on: ubuntu-latest
    needs:
      - extract-vars
    permissions:
      packages: write
      contents: read
      #
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          provenance: false
          platforms: |
            linux/arm64
            linux/amd64
          context: ./frontend
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{needs.extract-vars.outputs.env}}
          tags: |
            ghcr.io/fbsabalete/web-${{ env.IMAGE_NAME }}:latest
            ghcr.io/fbsabalete/web-${{ env.IMAGE_NAME }}:${{needs.extract-vars.outputs.image-tag}}



  deploy-ssh:
    name: Connect to ssh host and execute docker deploy
    runs-on: ubuntu-latest
    needs:
      - extract-vars
      - push-backend
      - push-frontend
    steps:
      - name: Execute deploy script on remote host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: ~/pipelines/scripts/deploy.sh ${{github.event.repository.name}} ${{needs.extract-vars.outputs.image-tag}} ${{needs.extract-vars.outputs.env}}